# Generated by Django 2.2.1 on 2019-05-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='number_of_times_clicked',
            field=models.IntegerField(default=0),
        ),
    ]
