# Generated by Django 2.2.1 on 2019-05-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
