# Generated by Django 2.2.1 on 2019-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='short',
            field=models.CharField(default='', max_length=10),
        ),
    ]
