# Generated by Django 2.2.1 on 2019-05-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_short_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
