# Generated by Django 2.2.1 on 2019-05-31 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_URL', models.CharField(default='', max_length=200)),
                ('short_URL', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(default='', max_length=200)),
                ('ip_addr', models.CharField(default='', max_length=200)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortenerapp.URL')),
            ],
        ),
    ]
