# Generated by Django 2.2.1 on 2019-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0004_auto_20190612_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=500)),
                ('short_url', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Short',
        ),
    ]
