# Generated by Django 2.2.1 on 2019-06-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='body',
        ),
        migrations.AlterField(
            model_name='chirp',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
