# Generated by Django 2.2.1 on 2019-06-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0002_auto_20190603_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='title',
            new_name='text',
        ),
    ]
