# Generated by Django 2.2.1 on 2019-06-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0003_auto_20190604_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='creater',
            new_name='creator',
        ),
    ]
